---
wordpress_host: 192.168.98.117

install_apache: true

install_oersi_plugin: true  # as long as the oersi-plugin is not available in the official wordpress-plugin-repository, we install it manually via a separate role

wp_title: wordpress-example

wp_admin_name: admin
wp_admin_email: root@wordpress.box
wp_admin_password: changeme

wp_config_reverse_proxy: true

dbname: wordpress
dbuser: wordpress
dbpassword: changeme
dbport: 3306

wordpress_installs:   # see - https://galaxy.ansible.com/oefenweb/wordpress
  - name: '{{ wp_title }}'
    dbname: '{{ dbname }}'
    dbuser: '{{ dbuser }}'
    dbpass: '{{ dbpassword }}'
    dbhost: localhost
    path: '/var/www/{{ wp_title }}'
    #document_root: '/var/www'
    url: 'http://{{ wordpress_host }}'
    title: '{{ wp_title }}'
    admin_name: '{{ wp_admin_name }}'
    admin_email: '{{ wp_admin_email }}'
    admin_password: '{{ wp_admin_password }}'
    themes:
      - name: twentytwelve
        activate: true
    plugins: []
    users: {}
    options: []
    queries: []

php_config:
  - key: upload_max_filesize
    value: 128M
  - key: post_max_size
    value: 128M
